"""initial schema

Revision ID: 70e6afc8d15d
Revises: 
Create Date: 2026-07-07 16:34:08.148104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e6afc8d15d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('choice', sa.String(), nullable=False),
    sa.Column('rejected_alternatives', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_predicate'), 'facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_facts_subject'), 'facts', ['subject'], unique=False)
    op.create_table('lifecycle_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_events_memory_id'), 'lifecycle_events', ['memory_id'], unique=False)
    op.create_table('lifecycle_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_states_memory_id'), 'lifecycle_states', ['memory_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_memory_type'), 'receipts', ['memory_type'], unique=False)
    op.create_index(op.f('ix_receipts_source'), 'receipts', ['source'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=False),
    sa.Column('validation', sa.Text(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_index(op.f('ix_receipts_source'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_memory_type'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_lifecycle_states_memory_id'), table_name='lifecycle_states')
    op.drop_table('lifecycle_states')
    op.drop_index(op.f('ix_lifecycle_events_memory_id'), table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_index(op.f('ix_facts_subject'), table_name='facts')
    op.drop_index(op.f('ix_facts_predicate'), table_name='facts')
    op.drop_table('facts')
    op.drop_table('entities')
    op.drop_table('decisions')
    # ### end Alembic commands ###
