#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# install-plugin.sh — Deploy the CMMS Hermes user-plugin shim.
#
# Creates $HERMES_HOME/plugins/memory_server/ with a small __init__.py
# that imports the real HermesProvider from the installed `memory_server`
# (composite-memory-mcp-server) package.
#
# Hermes v0.19 plugin discovery scans ~/.hermes/plugins/<name>/ for
# __init__.py with a register(ctx) function or MemoryProvider subclass.
# This shim provides the register() pattern.
#
# Prerequisites:
#   composite-memory-mcp-server pip-installed (editable or regular)
#      pip install -e /path/to/memory-server/
#
# Usage:
#   bash scripts/install-plugin.sh
#   # Or from repo root: make install-plugin
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Determine HERMES_HOME (respect existing, fall back to ~/.hermes)
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
PLUGIN_DIR="${HERMES_HOME}/plugins/memory_server"

echo "==> CMMS Hermes Plugin Installer"
echo "    HERMES_HOME:  ${HERMES_HOME}"
echo "    Target:       ${PLUGIN_DIR}"

# Verify the CMMS package is importable
python3 -c "import memory_server; print('memory_server v' + memory_server.__version__)" 2>/dev/null || {
    echo "ERROR: memory_server package not importable."
    echo "Run: pip install -e ${REPO_DIR}"
    exit 1
}

# Create plugin directory
mkdir -p "${PLUGIN_DIR}"

# Write the shim __init__.py
cat > "${PLUGIN_DIR}/__init__.py" << 'PYEOF'
"""Hermes user-plugin shim for CMMS (Composite Memory MCP Server).

Auto-generated by memory-server/scripts/install-plugin.sh.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def register(ctx) -> None:
    """Register CMMS HermesProvider as a memory provider."""
    try:
        from memory_server.plugins.hermes import HermesProvider
    except ImportError as exc:
        logger.error(
            "CMMS package not importable (%s). "
            "Ensure `pip install -e /path/to/memory-server/` has been run.",
            exc,
        )
        raise
    provider = HermesProvider()
    ctx.register_memory_provider(provider)
    logger.info("memory_server plugin registered via Hermes plugin shim")
PYEOF

# Write plugin.yaml metadata
cat > "${PLUGIN_DIR}/plugin.yaml" << 'PYEOF'
name: memory_server
version: 0.1.0
description: "CMMS (Composite Memory MCP Server) — native Hermes MemoryProvider"
author: CMMS Team
provides_memory: true
dependencies: []
PYEOF

echo ""
echo "==> Plugin installed successfully!"
echo "    ${PLUGIN_DIR}/__init__.py"
echo "    ${PLUGIN_DIR}/plugin.yaml"
echo ""
echo "Verify with: hermes memory status"

# Quick smoke test — imports from the installed Hermes package (no path guessing)
python3 -c "
from plugins.memory import find_provider_dir, _load_provider_from_dir
d = find_provider_dir('memory_server')
assert d is not None, 'memory_server plugin dir not found'
p = _load_provider_from_dir(d)
assert p is not None, 'memory_server provider could not be loaded'
assert p.name == 'memory_server', f'Expected name memory_server, got {p.name}'
print('Smoke check PASSED: memory_server plugin loaded successfully')
" 2>/dev/null || echo '  (smoke check skipped — plugins.memory not importable; run \"hermes memory status\" to verify)'
